<?php
require_once __DIR__ . '/../config/db.php';
require_role('admin');
$pdo = db();

if (isset($_GET['approve'])) {
    $pdo->prepare("UPDATE users SET status='approved' WHERE user_id=?")->execute([intval($_GET['approve'])]);
    header('Location: request.php'); exit;
}
if (isset($_GET['reject'])) {
    $pdo->prepare("UPDATE users SET status='rejected' WHERE user_id=?")->execute([intval($_GET['reject'])]);
    header('Location: request.php'); exit;
}
$req = $pdo->query("SELECT * FROM users WHERE role IN ('supplier','coordinator') ORDER BY CASE WHEN status='pending' THEN 0 ELSE 1 END, created_at DESC")->fetchAll();
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Verification Requests</title><style>body{margin:0;background:#050505;color:white;font-family:Segoe UI,sans-serif}.wrap{display:flex;min-height:100vh}.side{width:260px;background:#111;border-right:1px solid rgba(243,197,71,.18);padding:28px}.brand{color:#f3c547;font-size:28px;font-weight:900;margin-bottom:30px}.side a{display:block;color:white;text-decoration:none;padding:14px;border-radius:12px;margin:8px 0}.side a:hover,.active{background:rgba(243,197,71,.12);color:#f3c547!important}.main{flex:1;padding:36px}table{width:100%;border-collapse:collapse;background:#111;border-radius:18px;overflow:hidden}td,th{padding:14px;border-bottom:1px solid rgba(255,255,255,.08);text-align:left;vertical-align:top}th{color:#f3c547}.btn{padding:8px 12px;border-radius:10px;text-decoration:none;margin-right:6px;display:inline-block}.ok{background:#123d25;color:#9cffbd}.bad{background:#3d1212;color:#ff9b9b}.file{color:#f3c547}.pending{color:#f3c547}.approved{color:#9cffbd}.rejected{color:#ff9b9b}.thumb{width:95px;height:95px;object-fit:cover;border-radius:12px;border:1px solid rgba(243,197,71,.25);margin:4px}</style></head><body><div class="wrap"><div class="side"><div class="brand">EventIntel Admin</div><a href="admin.php">Dashboard</a><a class="active" href="request.php">Verification Requests</a><a href="../auth/logout.php">Logout</a></div><main class="main"><h1>Supplier / Coordinator Verification</h1><p>Compare uploaded Valid ID and the live face capture before approving.</p><table><tr><th>Name</th><th>Role</th><th>Business</th><th>Status</th><th>ID / Permit / Face Scan</th><th>Action</th></tr><?php foreach($req as $u):?><tr><td><?= esc(trim(($u['first_name'] ?? '').' '.($u['last_name'] ?? '')) ?: ($u['full_name'] ?? $u['username'])) ?><br><small><?= esc($u['email']) ?></small><br><small><?= esc($u['phone'] ?? '') ?></small></td><td><?= esc($u['role']) ?></td><td><?= esc($u['business_name']) ?><br><small><?= esc($u['business_address']) ?></small></td><td class="<?= esc($u['status']) ?>"><?= esc($u['status']) ?></td><td><?php if($u['valid_id']):?><a class="file" target="_blank" href="../<?= esc($u['valid_id']) ?>">Valid ID</a><br><?php endif;?><?php if($u['business_permit']):?><a class="file" target="_blank" href="../<?= esc($u['business_permit']) ?>">Permit</a><br><?php endif;?><?php if($u['face_capture']):?><a class="file" target="_blank" href="../<?= esc($u['face_capture']) ?>">Live Face Capture</a><br><img class="thumb" src="../<?= esc($u['face_capture']) ?>"><?php endif;?></td><td><?php if($u['status']==='pending'):?><a class="btn ok" href="?approve=<?= $u['user_id'] ?>">Approve</a><a class="btn bad" href="?reject=<?= $u['user_id'] ?>">Reject</a><?php else:?>—<?php endif;?></td></tr><?php endforeach;?></table></main></div></body></html>
